---
- apt: name={{ item }} state=installed
  with_items:
    - apache2
    - apache2-mpm-event
    - uwsgi
    - uwsgi-plugin-php
    - php5-mysql
    - php5-adodb
    - php5-imagick
    - php5-mcrypt
    - php5-memcache
    - memcached

# need to enable mod-proxy since mod-proxy-uwsgi depends on it
- shell: a2enmod proxy creates=/etc/apache2/mods-enabled/proxy.load

- apt: name={{ item }} state=installed
  with_items:
    - libapache2-mod-proxy-uwsgi

