---
# the equivalent of "mysql_secure_installation", but without needing user input
# inspired by http://stackoverflow.com/a/27759061
- name: secure mariadb
  shell: mysql -e "{{ item }}"
  # if we re-execute these, some might fail, so ignore those
  ignore_errors: yes
  with_items:
    - "UPDATE mysql.user SET Password = PASSWORD('{{ mysql_root_password }}') WHERE User = 'root'"
    - "DROP USER ''@'localhost'"
    - "DROP USER ''@'$(hostname)'"
    - "DROP DATABASE test"
    - "FLUSH PRIVILEGES"

